# Generated by Django 3.2 on 2023-02-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=55)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'TodoList',
                'verbose_name_plural': 'TodoLists',
            },
        ),
    ]
