# Generated by Django 3.2 on 2023-02-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_slottime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SLottime',
        ),
    ]
